# Generated by Django 4.0.6 on 2022-07-11 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resenia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelicula', models.CharField(max_length=25)),
                ('sinopsis', models.IntegerField()),
                ('fecha_creacion', models.DateField(null=True)),
                ('genero', models.CharField(max_length=25)),
                ('director', models.CharField(max_length=25)),
            ],
        ),
    ]
