# Generated by Django 4.0.6 on 2022-07-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=35)),
                ('caracteres', models.IntegerField()),
                ('fecha_creacion', models.DateField(null=True)),
                ('genero', models.CharField(max_length=20)),
                ('autor', models.CharField(max_length=15)),
            ],
        ),
    ]
